### ISSUE TITLE
V2 doesnt allow the character a or d to have capital letters

### ISSUE THREAD

**Issue by herovaxy** [Niklasw99/autohotkeyscriptsnapiesttappyest#1]
My preferred version is V2 but I noticed that it doesn't allow the character to become capital letters when caps is on. Kindly fix this thank you.

**Comment by Niklasw99** [comment]
Adding Logic to it would make it slower. 
i will no be adding this feature to the V2. 
you can add it by checking for a shift + a
or shift + b for capital letters or something else. 

good luck
